In [1]:
from objetos import *
from function import *
import pandas as pd 
import random as rd
import numpy as np

In [2]:
# input_file=input("Please insert the name of the file")

df= pd.read_excel("Teste.xlsx",header=0)


In [3]:
df= pd.DataFrame(df)
df2=df.groupby(df["Component"])
df.head()

Component Attribute  Prob_of_Failure
0     motor      ATT1               10
1     motor      ATT2               25
2       fan      ATT3               20

In [4]:
components_unique= df['Component'].unique()
#Creating Components Objects
list_comp = [Component(name=component_name) for component_name in components_unique]
list_comp

Component created named motor
Component created named fan


[<objetos.Component at 0x1c799e1d150>, <objetos.Component at 0x1c799f10f10>]

In [5]:
relacoes={}

for index, line in df.iterrows():
    component = line['Component']
    attribute = line['Attribute']
    prob_failure = line['Prob_of_Failure']
    
    if component not in relacoes:
        relacoes[component] = {}

    
    relacoes[component][attribute] = prob_failure
    
relacoes


{'motor': {'ATT1': 10, 'ATT2': 25}, 'fan': {'ATT3': 20}}

In [6]:
attributos_= []
for comp in list_comp:
    for attr in relacoes[comp.name]:
        attributos_.append(Propriety(component=comp, name=attr, risk=relacoes[comp.name][attr]))
        
attributos_

Atribute named ATT1 linked to motor
Atribute named ATT2 linked to motor
Atribute named ATT3 linked to fan


# Adding ways that things fails!

In [7]:
# attributos_[2].addFailureMode(['Excess','Loss'],[50,50])

# NOTE: in this part we are supposed to add link. Don't know how to do it yet. 

In [8]:
links,attrs=createMatrix(components=list_comp)
links

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [9]:
createLink(matrix=links,attribute1=attributos_[0], attribute2=attributos_[1],attribute_list=attributos_, time=1, risk=100 )


In [10]:

Mov=Behaviour(name="Movement")
Mov.addCondition(attributos_[1])
Mov.addCondition(attributos_[0])
Inf_Iteraction= Behaviour(name="teste")

behavi=[Mov,Inf_Iteraction]



Behaviour created named Movement
Created a condtion that ATT2 has to work for  Movement to continue working
Created a condtion that ATT1 has to work for  Movement to continue working
Behaviour created named teste


In [11]:
State_machine(components=list_comp,behaviour=behavi,matrix=links,attrs= attributos_)

[[[  0   0]
  [100   1]
  [  0   0]]

 [[100   1]
  [  0   0]
  [  0   0]]

 [[  0   0]
  [  0   0]
  [  0   0]]]
============================CURRENTLY ON TICK 0===============================
----------------------------Proprieties-------------------------------
ATT1 from motor is Working
ATT2 from motor is Working
ATT3 from fan *just* failed on tick: 0
----------------------------Behaviour-------------------------------
Movement working
teste working
============================CURRENTLY ON TICK 1===============================
----------------------------Proprieties-------------------------------
ATT1 from motor is Working
ATT2 from motor *just* failed on tick: 1
ATT3 from fan failed on tick 0, which is 1 ticks ago
----------------------------Behaviour-------------------------------
Movement working
teste working
============================CURRENTLY ON TICK 2===============================
----------------------------Proprieties-------------------------------
ATT1 from motor is Wor

c:\Users\nicol\OneDrive\Área de Trabalho\Python\Escaralhando\function.py:123: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'Failed Behaviour': mensagem_erro}, ignore_index=True)


===================================DONE================================================
CSV saved in: Simulation/Simulation_29_11_2023_13_23.csv
Time to complete 10.012986183166504 seconds
[[[  0   0]
  [100   1]
  [  0   0]]

 [[100   1]
  [  0   0]
  [  0   0]]

 [[  0   0]
  [  0   0]
  [  0   0]]]
[[[  0   0]
  [100   1]
  [  0   0]]

 [[100   1]
  [  0   0]
  [  0   0]]

 [[  0   0]
  [  0   0]
  [  0   0]]]


In [13]:
links

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])